export const siteConfig = {
  name: "Nguyen Tran Anh (SatohJiro)",
  vietnameseName: "Nguyễn Trần Anh",
  title: "Nguyen Tran Anh | Software Engineer (Full-Stack & Frontend)",
  vietnameseTitle: "Nguyễn Trần Anh | Kỹ sư Phần mềm (Full-Stack & Frontend)",
  description: "Portfolio of Nguyen Tran Anh (SatohJiro) - Software Engineer & Valedictorian of Class 2019 (Nong Lam University). 3+ years experience with ReactJS, Next.js, Vue.js, Spring Boot, FastAPI, and GPT-4 AI integration.",
  vietnameseDescription: "Hồ sơ cá nhân của Nguyễn Trần Anh (SatohJiro) - Kỹ sư Phần mềm & Thủ khoa ĐH Nông Lâm TP.HCM. Hơn 3 năm kinh nghiệm thực tế với ReactJS, Next.js, Vue.js, Spring Boot, FastAPI và ứng dụng AI GPT-4.",
  url: "https://satohjiro.github.io",
  ogImage: "https://satohjiro.github.io/og-image.png",
  links: {
    github: "https://github.com/SatohJiro",
    linkedin: "https://www.linkedin.com/in/satohjiro/",
    portfolio: "https://satohjiro.github.io/",
    email: "mailto:trananhq2345@gmail.com",
    phone: "tel:+84989702459",
  },
  contact: {
    email: "trananhq2345@gmail.com",
    phone: "(+84) 98 970 2459",
    displayPhone: "0989 702 459",
    locationVi: "TP. Hồ Chí Minh, Việt Nam",
    locationEn: "Ho Chi Minh City, Vietnam",
  },
  navItems: [
    { id: "home", href: "#home", label: { en: "Home", vi: "Trang chủ" }, icon: "Home" },
    { id: "about", href: "#about", label: { en: "About", vi: "Giới thiệu" }, icon: "User" },
    { id: "experience", href: "#experience", label: { en: "Experience", vi: "Kinh nghiệm" }, icon: "Briefcase" },
    { id: "projects", href: "#projects", label: { en: "Projects", vi: "Dự án" }, icon: "Layers" },
    { id: "skills", href: "#skills", label: { en: "Skills", vi: "Kỹ năng" }, icon: "Cpu" },
    { id: "awards", href: "#awards", label: { en: "Honors", vi: "Vinh danh" }, icon: "Award" },
    { id: "contact", href: "#contact", label: { en: "Contact", vi: "Liên hệ" }, icon: "Mail" },
  ],
};
